### ISSUE TITLE
js instead ts?

### ISSUE THREAD

**Issue by jetic83** [tuvia-r/openseadragon-select-plugin#8]
Thanks for the nice plugin. Is there a way to use it as pure javascript (not as a module)?

Thanks!

**Comment by tuvia-r** [comment]
you can now use https://unpkg.com/openseadragon-select-plugin@1.0.20/dist/index.umd.min.js, and https://unpkg.com/openseadragon-select-plugin@1.0.20/dist/index.min.mjs

**Comment by jetic83** [comment]
Thanks a lot!
I wanted to import index.min.mjs but get following error:

`openseadragon-select-plugin.min.mjs:1 Uncaught SyntaxError: Unexpected token 'export' (at openseadragon-select-plugin.min.mjs:1:13075)`

Seems like this is a Node.js depending module. Is there a way to use it without Node.js? My JS does not know export nor require.
